### ISSUE TITLE
User-friendly error messages

### ISSUE THREAD

**Issue by ddugovic** [ettolrach/open-lilybot#3]
Honestly, this bot is amazing.

Unfortunately I am new to Lilypond syntax, so when I submit `$lilypond -dpreview ```\relative c { \clef bass e8, e e, e e, e e, e }``` ` instead of simply `error: octave marks must precede duration` I see:

```
An error has occured: 
Error: Command failed: lilypond -dpreview --output=generatedFiles code.ly 
Changing working directory to: `generatedFiles'
Processing `code.ly'
Parsing...
/home/turing/open-lilybot/code.ly:1:28: error: octave marks must precede duration
\relative c { \clef bass e8
                           , e e, e e, e e, e }
code.ly:1: warning: no \version statement found, please add

\version "2.20.0"

for future compatibility
Interpreting music...
Preprocessing graphical objects...
Finding the ideal number of pages...
Fitting music on 1 page...
Drawing systems...
Layout output to `/tmp/lilypond-ZnDxfM'...
Converting to `code.pdf'...
Deleting `/tmp/lilypond-ZnDxfM'...
Layout output to `code.preview.eps'...
Converting to `code.preview.pdf'...
Converting to PNG...
Deleting `code.preview.eps'...
fatal error: failed files: "code.ly"

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**Comment by ettolrach** [comment]
Unfortunately that isn't up to me and is how Lilypond responds to error messages. I could do a user friendly "an error occured", but I prefer giving a detailed error.

**Comment by ddugovic** [comment]
OK, that makes sense.  In my copy of the bot I've hard-coded a `\version` tag to de-clutter this message a bit.

FYI I just deployed this bot to the cloud as https://top.gg/bot/830798208158138388

**Comment by ettolrach** [comment]
I'm looking over some of the code I wrote and improving some of the user-friendliness myself. Expect an update soonish.
